import type { Metadata } from "next";

import "./globals.css";
import TanstackProvider from "@/provider/tanstack-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" font-satoshi"}>
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}
